spring.application.name=blindspot-api

google.places.api-key=${GOOGLE_PLACES_API_KEY:}
google.places.base-url=https://places.googleapis.com

geoapify.routing.api-key=${GEOAPIFY_API_KEY:}
geoapify.routing.base-url=https://api.geoapify.com
